#!/usr/bin/env bash
#This is task 11
while IFS=":" read -r cut_username cut_user_id cut_home
do
    passwd_row=$(grep "^${cut_username}:" /etc/passwd)
    

    IFS=":" read -r username password user_id group_id user_id_info home_directory shell <<< "$passwd_row"
    
    : "${username:=$cut_username}"
    : "${user_id:=$cut_user_id}"
    : "${home_directory:=$cut_home}"

    echo "The user $username is part of the ${group_id:-unknown} gang, lives in $home_directory and rides ${shell:-nothing}. $user_id's place is protected by the passcode ${password:-x}, more info about the user here: $user_id_info"

done < <(bash 11-read_and_cut)

