#!/usr/bin/env bash
#This is file 5
i=1
while (( i <= 10 ))
do
   
   if (( i == 4 ))
   then
      echo "bad luck"
elif (( i == 8 ))
then
echo "good luck"
else 
echo "Best school"
   fi
   i=$((i + 1))
done

