#!/usr/bin/env bash
#This is task 6
hour=0
while (( hour <= 12 ))
do
   echo "Hour: $hour"
   minute=1
   while (( minute <= 59 ))
   do
      echo "$minute"
      minute=$((minute + 1))
   done
   hour=$((hour + 1))
done

