#!/usr/bin/env bash
#task 11
PID_FILE="/var/run/my_process.pid"
SCRIPT_PATH="./manage_my_process"

case "$1" in
    start)
        "$SCRIPT_PATH" > /dev/null 2>&1 &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat "$PID_FILE")"
            rm -f "$PID_FILE"
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat "$PID_FILE")"
            rm -f "$PID_FILE"
        fi
        "$SCRIPT_PATH" > /dev/null 2>&1 &
        echo $! > "$PID_FILE"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

